### PR TITLE
Feature/filter by children

### PR DESCRIPTION
**Pull request by RWOverdijk**
Allow filtering parent resultset by child criteria. 
Provides the requested functionalities from [#597](https://github.com/balderdashy/waterline/issues/597), [#645](https://github.com/balderdashy/waterline/issues/645), [#2238](https://github.com/balderdashy/sails/issues/2238), [#48](https://github.com/balderdashy/sails-redis/issues/48) and [#2392](https://github.com/balderdashy/sails/issues/2392)

I've implemented a couple of additional methods, as well of the concept of scoping.

Scoping the current criteriaParser to a different (association) table will allow expanding of criteria to said associations. By using a scope, it will also automatically assume you're talking about a population, and create the alias.

**Notes:**
- This doesn't work if you don't populate the model you're filtering because the alias of the join table won't exist.
- It treats children differently from criteria (as it should) and doesn't alter the default behavior.

~~Works, except for missing passing of `currentTable`.  I made a booboo in the code (`parentSchema = this.schema[parent]`, which won't work for properties obviously.). This has one single side effect, being that case sensitivity detection doesn't work.~~

~~I'll have to refactor by either changing and restoring the current scopes (currentTable, currentSchema etc) or by passing along the table (association) we're expanding for.~~

~~The reason I haven't implemented this yet is because I'm not sure if you'll approve of my approach :) Also, I'm about to head out for some meetings and just wanted to put this out there for the feedback.~~

``` javascript
  sails.models.foo.find({
    or : [
      {
        color: 'red'
      },
      {
        color: 'blue'
      },
      {
        color: 'grey'
      },
      {
        bat : {
          color_g : 'yellow'
        }
      },
      {
        bat : {
          color_g : 'blue'
        }
      }
    ],
    bat : {
      color_h : 'red', // red
      or : [
        {
          color_i : ['pink', 'purple', 'green']
        },
        {
          color_i : {
            '>' : 'black'
          }
        },
        {
          color_i: 'yellow'
        }
      ]
    }
  }).populate('bat').exec(function (error, data) {
    if (error) {
      return console.log(error);
    }

    console.log(data);
  });
};
```

Nicely creates:

``` sql
SELECT 
    `foo`.`color`,
    `foo`.`id`,
    `foo`.`createdAt`,
    `foo`.`updatedAt`,
    `foo`.`bar`,
    `foo`.`bat`,
    `foo`.`baz`,
    `__bat`.`color_g` AS `bat___color_g`,
    `__bat`.`color_h` AS `bat___color_h`,
    `__bat`.`color_i` AS `bat___color_i`,
    `__bat`.`id` AS `bat___id`,
    `__bat`.`createdAt` AS `bat___createdAt`,
    `__bat`.`updatedAt` AS `bat___updatedAt`
FROM
    `foo` AS `foo`
        LEFT OUTER JOIN
    `bat` AS `__bat` ON `foo`.`bat` = `__bat`.`id`
WHERE
    ((`foo`.`color` = 'red')
        OR (`foo`.`color` = 'blue')
        OR (`foo`.`color` = 'grey')
        OR (`__bat`.`color_g` = 'yellow')
        OR (`__bat`.`color_g` = 'blue'))
        AND `__bat`.`color_h` = 'red'
        AND ((`__bat`.`color_i` IN ('pink' , 'purple', 'green'))
        OR (`__bat`.`color_i` > 'black')
        OR (`__bat`.`color_i` = 'yellow'))
```

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@tjwebb You promised ^_^

**Comment by tjwebb** [comment]
I am looking at it, this just isn't the sort of thing that gets merged instantly :)

Can you include any tests?

**Comment by RWOverdijk** [comment]
@tjwebb Understandable. And I would, if there was a test suite at all.

**Comment by RWOverdijk** [comment]
After the tests, I'm going to check if I can take a different approach to this. It looks like it's possible to add instructions for the children. If that's the case, that'd be a far more elegant solution.

**Comment by RWOverdijk** [comment]
@tjwebb If you add the travis hook you can see the new tests passing. All I had to do for BC, was add a space. It wasn't breaking, it just made the generated query slightly different.

The tests can be seen here https://travis-ci.org/RWOverdijk/waterline-sequel/builds/54326941 before you attach the travis hook.

**Comment by RWOverdijk** [comment]
@tjwebb Any news?

**Comment by aars** [comment]
+1

**Comment by wayne-o** [comment]
+1

**Comment by dmarcelino** [comment]
@RWOverdijk, in your `.find()` example:

``` javascript
      {
        bat : {
          color_g : 'yellow'
        }
      },
```

Would this need to use the actual table column name `color_g` or it also supports the case where model attribute name is different than columnName?

I'm referring the case where one declares the attribute as such:
``` javascript
attributes: {
  myColor: {
    type: 'string',
    columnName: 'color_g'
  }
}
```

**Comment by RWOverdijk** [comment]
@dmarcelino It should work with custom table names, too. I didn't change resolve logic so it should behave the way it usually does.

**Comment by RWOverdijk** [comment]
I'm about to submit a new PR to allow sorting by associations, too. Can we please do something with this PR?

**Comment by wayne-o** [comment]
We have had to add columnName to our models so that instead of the foreign key name being just the name of the model it is now nameOfModelId (with Id at the end) - now I am getting the following error:

```
error:  Error (E_UNKNOWN) :: Encountered an unexpected error
error: operator does not exist: integer ~~* unknown
    at Connection.parseE (/Users/waynedouglas/sonatribe-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/waynedouglas/sonatribe-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/waynedouglas/sonatribe-api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

Is this related to what @dmarcelino was mentioning above?

**Comment by dmarcelino** [comment]
Hi @wayne-o, this change hasn't been released to npm yet, are you using the github version? And which adapter are you using?

**Comment by wayne-o** [comment]
Hey - yeah using the GH version - I am using it through the postgres adapter

On Fri, Apr 17, 2015 at 10:30 AM, Dário <notifications@github.com> wrote:

> Hi @wayne-o <https://github.com/wayne-o>, this change hasn't been
> released to npm yet, are you using the github version? And which adapter
> are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/waterline-sequel/pull/27#issuecomment-93952049>
> .
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by dmarcelino** [comment]
@RWOverdijk, can you take a look at https://github.com/balderdashy/waterline-sequel/pull/27#issuecomment-93919972? Thanks

**Comment by RWOverdijk** [comment]
@wayne-o Could you try and explain your issue a bit more detailed? It's very difficult to understand what you're trying to say.

**Comment by wayne-o** [comment]
Sorry mate, so this query works:

https://gist.github.com/wayne-o/35a720a0b27341807483

When used with models like this:

https://gist.github.com/wayne-o/b211790056937da94b6a

But not with models like this:

https://gist.github.com/wayne-o/653183531bc78a1a0ec9

So basically - without columnName definitions.

**Comment by RWOverdijk** [comment]
@wayne-o That sort of makes sense. I think it uses the column name in stead of the potential alias in your case.

**Comment by wayne-o** [comment]
Is there a fix for this? I have tried looking at the PR for this and it's a little over my node knowledge atm! :)

**Comment by RWOverdijk** [comment]
@wayne-o I'll try to add support for your use case as soon as I've fixed the tests. It's just quite low on my list of priorities because it's not a bug but a missing feature (and I'm quite busy).

**Comment by wayne-o** [comment]
If you can give me some pointers I'd happily jump in and help

**Comment by RWOverdijk** [comment]
@wayne-o I suppose around here: https://github.com/balderdashy/waterline-sequel/pull/27/files#diff-9fad2d09c9989920cbf45599c3e6eabcR473

**Comment by wayne-o** [comment]
Hmmmm... here is the generated SQL for that query (i've omitted the columns list to make it less painful on the eye):

```SELECT 
"listingevent"."name", "listingevent"."timeZone", "listingevent"."tzOffset", "listingevent"."slug", 
"listingevent"."start", "listingevent"."end", "listingevent"."eventInstanceSlug", "listingevent"."id", 
"listingevent"."createdAt", "listingevent"."updatedAt", "listingevent"."locationId", 
"listingevent"."eventInstanceId", "listingevent"."artistId", "__location"."name" 
AS "locationId___name", "__location"."deleted" AS "locationId___deleted",
 "__location"."priority" AS "locationId___priority", "__location"."id" AS "locationId___id", "__location"."createdAt" AS "locationId___createdAt",
  "__location"."updatedAt" AS "locationId___updatedAt", "__location"."eventInstanceId" AS "locationId___eventInstanceId" 
  
  FROM "listingEvent" AS "listingevent"  LEFT OUTER JOIN "location" AS "__location" ON "listingevent"."locationId" = "__location"."id" 
  WHERE LOWER("listingevent"."eventInstanceSlug") = 'ultra-music-festival-2015' AND ((LOWER("listingevent"."name") ILIKE 'hen%' )
   OR ("listingevent"."locationId" ILIKE 'hen%' ))  
  ORDER BY "listingevent"."start" ASC LIMIT 40 OFFSET 0"
```

And here is the query after I have tweaked it to work:

```
SELECT 
"listingevent"."name", "listingevent"."timeZone", "listingevent"."tzOffset", "listingevent"."slug", 
"listingevent"."start", "listingevent"."end", "listingevent"."eventInstanceSlug", "listingevent"."id", 
"listingevent"."createdAt", "listingevent"."updatedAt", "listingevent"."locationId", 
"listingevent"."eventInstanceId", "listingevent"."artistId", "__location"."name" 
AS "locationId___name", "__location"."deleted" AS "locationId___deleted",
 "__location"."priority" AS "locationId___priority", "__location"."id" AS "locationId___id", "__location"."createdAt" AS "locationId___createdAt",
  "__location"."updatedAt" AS "locationId___updatedAt", "__location"."eventInstanceId" AS "locationId___eventInstanceId" 
  
  FROM "listingEvent" AS "listingevent"  LEFT OUTER JOIN "location" AS "__location" ON "listingevent"."locationId" = "__location"."id" 
  WHERE LOWER("listingevent"."eventInstanceSlug") = 'ultra-music-festival-2015' AND ((LOWER("listingevent"."name") ILIKE 'hen%' )
   OR ("__location"."name" ILIKE 'hen%' ))  
  ORDER BY "listingevent"."start" ASC LIMIT 40 OFFSET 0
```

You'll notice is is incorrectly doing this:  ``` OR ("listingevent"."locationId" ILIKE 'hen%' )) ``` where it should be doing ``` OR ("__location"."name" ILIKE 'hen%' )) ```

Any help really appreciated :)

**Comment by RWOverdijk** [comment]
@wayne-o Could you please clean up your example? Make a smaller example. I'll help :)

**Comment by wayne-o** [comment]
Just cleaned up the SQL - what sort of example do you want? a fresh sails repo?

**Comment by RWOverdijk** [comment]
@wayne-o A small one. Two models, simple query.

**Comment by RWOverdijk** [comment]
Particularly this file is dreadful: https://gist.github.com/wayne-o/35a720a0b27341807483

But it'd be incredibly helpful if the example just consisted out of two models. Keeping it simple :)

**Comment by wayne-o** [comment]
Now getting a different error all together but the repo is here https://github.com/wayne-o/filter_test

```
Error (E_UNKNOWN) :: Encountered an unexpected error
error: column someparent.children does not exist
    at Connection.parseE (/Users/waynedouglas/filter-demo/api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/waynedouglas/filter-demo/api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/waynedouglas/filter-demo/api/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

Details:  error: column someparent.children does not exist
```

**Comment by wayne-o** [comment]
I've reverted back to SQL for now as this seems a bit unstable - when I get the chance I will look into this properly as I am a great fan of this approach

**Comment by RWOverdijk** [comment]
@wayne-o It's using the wrong association name to pull this off in the code. I don't have the time right now, but when I do I'll take a look.

**Comment by wayne-o** [comment]
No worries mate - I wish I could figure it out but ATM it's a little too much for me in terms of time - I did give it a shot though :) 

I love this approach so thanks for getting the leg work done - look forward to the update. My code is now looking even more horrendous with SQL in it so this will be a welcome update!

**Comment by RWOverdijk** [comment]
@wayne-o Looking into this more... I don't think this should work. You're naming the column, not the collection. The key remains the key and I believe that's how it should work...

I've implemented your requested feature in #44 (and fixed a bug, too). It generates the exact same query in the end, so my question to you is... Why do you want to use the columnName (alias) as a key in association criteria? Just curious.

**Comment by wayne-o** [comment]
Not sure I explained myself then - all I am doing is adding the foreign key
column name to the model.

I am not using that column in the query at all.

The query that worked before adding the column name attribute did not after
adding it.

Does that make sense?

On Wed, Apr 22, 2015 at 2:42 PM, Wesley Overdijk <notifications@github.com>
wrote:

> @wayne-o <https://github.com/wayne-o> Looking into this more... I don't
> think this should work. You're naming the column, not the collection. The
> key remains the key and I believe that's how it should work...
>
> I've implemented your requested feature in #44
> <https://github.com/balderdashy/waterline-sequel/pull/44> (and fixed a
> bug, too). It generates the exact same query in the end, so my question to
> you is... Why do you want to use the columnName (alias) as a key in
> association criteria? Just curious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/waterline-sequel/pull/27#issuecomment-95182108>
> .
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by RWOverdijk** [comment]
@wayne-o Please continue this conversation based on #44. I think that PR might fix your problem. If not, we'll discuss this further :)

**Comment by fikrivoxel** [comment]
this method still working ?

**Pull request merged**
