### PR TITLE
Add support for raw expressions in a groupBy statement

### PR DESCRIPTION
**Pull request by kevinob11**
This is to solve balderdashy/sails-postgresql#164.

### CODE REVIEW

**Comment by devinivy** [comment]
Are any additional changes required in other repos to add this support?

**Comment by kevinob11** [comment]
I expect not as it uses the default groupBy syntax, extending its abilities to support expressions while still keeping the default behavior the same.

**Comment by devinivy** [comment]
@particlebanana mind taking a look?  I'm re-running CI since this is so old.  Looking to resolve https://github.com/balderdashy/sails-postgresql/issues/164.

**Comment by kevinob11** [comment]
Let me know if I need to rebase or anything.

**Comment by kevinob11** [comment]
Can we merge this? I just had to rebase my fork of sails postgresql because I've been waiting on this.

**Comment by devinivy** [comment]
The work done looks good to me.  CC @particlebanana

**Comment by particlebanana** [comment]
I'll add this to my to-do list for the day. Sorry for the delay @kevinob11

**Comment by kevinob11** [comment]
Np, thanks! Just make a release happen soon and we'll call it even :)

**Comment by particlebanana** [comment]
This looks good. I guess aggregations aren't really in beta anymore so we should work on some docs for them. If anyone would like to take a pass on that for waterline-docs thats would be great!

**Comment by particlebanana** [comment]
published `0.5.2`

**Comment by kevinob11** [comment]
Thanks! I'll take a peek at docs, but i'm a bit buried this week and next.

**Comment by kevinob11** [comment]
Ok updated docs for your review! balderdashy/waterline-docs#107, give em' a look and let me know!

**Pull request merged**
