### PR TITLE
Test setup

### PR DESCRIPTION
**Pull request by RWOverdijk**
Test setup..

Very basic for now. The idea is that you just add query meta to the test/queries dir. Now I'm manually adding those to be tested, but they can (and will) be automated.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@tjwebb Happy now? I'll addm ore just so we can merge the other PR :)

**Comment by tjwebb** [comment]
I am very happy :) Thanks. My goal is to review and merge before the
weekend.

**Comment by RWOverdijk** [comment]
@tjwebb cool cool. I've added some magic to make writing tests easier. I'll add a couple more tests tomorrow in this manner, and after that add the complex one ensuring it all still works.

**Comment by RWOverdijk** [comment]
@tjwebb Done. The tests can be extended at will, but I think this is a good start.

**Pull request merged**
